# Generated by Django 4.0.3 on 2022-12-05 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('data_nascimento', models.DateField()),
                ('data_falecimento', models.DateField(blank=True, null=True)),
                ('local_nascimento', models.CharField(max_length=100)),
                ('biografia', models.TextField(default='Biografia do Autor')),
                ('rosto', django_resized.forms.ResizedImageField(crop=None, default='../static/assets/img/sem_rosto.jpg', force_format=None, keep_meta=True, quality=80, scale=None, size=[200, 292], upload_to='img/')),
                ('curriculo_lattes', models.CharField(blank=True, max_length=16, null=True, verbose_name='Currículo Lattes')),
            ],
            options={
                'verbose_name_plural': 'Autores',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=40, verbose_name='Descrição')),
            ],
            options={
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('edicao', models.IntegerField(blank=True, default=1, null=True, verbose_name='Edição')),
                ('titulo', models.CharField(max_length=100)),
                ('ano', models.DateField()),
                ('editora', models.CharField(blank=True, max_length=40, null=True)),
                ('num_page', models.IntegerField(blank=True, null=True, verbose_name='Nº Páginas')),
                ('capa', django_resized.forms.ResizedImageField(crop=None, default='../static/assets/img/sem_capa.jpg', force_format=None, keep_meta=True, quality=80, scale=None, size=[200, 292], upload_to='img/')),
                ('resumo', models.TextField(default='Resumo da Obra')),
                ('consulta', models.PositiveIntegerField(default=1)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.autor')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.categoria')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Livros',
            },
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=5)),
                ('status', models.CharField(choices=[('1', 'Disponível'), ('2', 'Indisponível')], default=1, max_length=2)),
                ('localizacao', models.CharField(blank=True, max_length=15, null=True, verbose_name='Localização')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Exemplares',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emprestimo', models.DateField()),
                ('data_retorno', models.DateField()),
                ('status', models.CharField(choices=[('1', 'Pendente'), ('2', 'OK')], default=1, max_length=2)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_created', models.DateTimeField(auto_now=True)),
                ('exemplar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.exemplar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Empréstimos',
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.TextField()),
                ('data_comentario', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Lido', 'Lido'), ('Não Lido', 'Não Lido')], default='Não Lido', max_length=10)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.livro')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Comentários',
            },
        ),
    ]
