# Generated by Django 2.2.12 on 2021-11-19 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(max_length=70)),
                ('curriculo_lattes', models.CharField(max_length=16, verbose_name='Currículo Lattes')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('edicao', models.IntegerField(verbose_name='Edição')),
                ('titulo', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=4)),
                ('editora', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
    ]
