# Generated by Django 2.2.12 on 2021-11-20 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='autor',
            new_name='nome',
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Livro')),
            ],
        ),
    ]
