# Generated by Django 4.0.3 on 2022-11-26 07:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='usuario',
            field=models.ForeignKey(default='Desconhecido', on_delete=django.db.models.deletion.CASCADE, related_name='student_id_fk', to=settings.AUTH_USER_MODEL),
        ),
    ]
