# Generated by Django 2.2.12 on 2021-11-20 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_auto_20211119_2207'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Autor',
        ),
        migrations.DeleteModel(
            name='Exemplar',
        ),
        migrations.DeleteModel(
            name='Livro',
        ),
    ]
