# Generated by Django 4.0.3 on 2022-11-26 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_alter_borrow_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='usuario',
            new_name='student',
        ),
    ]
