# Generated by Django 4.1.4 on 2022-12-08 10:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0002_borrow_delete_emprestimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastros.exemplar', verbose_name='Exemplar'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='borrowing_date',
            field=models.DateField(verbose_name='Data de retirada'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Horário de Criação'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='date_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de criação'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='return_date',
            field=models.DateField(verbose_name='Data de devolução'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
