# Generated by Django 2.2.12 on 2021-11-20 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastros', '0003_auto_20211119_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=70)),
                ('curriculo_lattes', models.CharField(max_length=16, verbose_name='Currículo Lattes')),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13)),
                ('edicao', models.IntegerField(verbose_name='Edição')),
                ('titulo', models.CharField(max_length=100)),
                ('ano', models.CharField(max_length=4)),
                ('editora', models.CharField(max_length=40)),
                ('categoria', models.CharField(max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Autor')),
            ],
        ),
        migrations.CreateModel(
            name='Exemplar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Livro')),
            ],
        ),
    ]
