# Generated by Django 2.2.12 on 2021-11-25 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0004_autor_exemplar_livro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=20, verbose_name='Descrição')),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdeExemplar', models.IntegerField(blank=True, help_text='Informar apenas se o tipo de material for igual a LIVRO!', null=True, verbose_name='Qtde. de Exemplares')),
                ('titulo', models.CharField(blank=True, help_text='Informar o tipo de material não for um LIVRO!', max_length=100, null=True)),
                ('autor', models.CharField(blank=True, help_text='Informar o tipo de material não for um LIVRO!', max_length=70, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='livro',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Exemplar',
        ),
        migrations.AddField(
            model_name='material',
            name='livro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Livro'),
        ),
        migrations.AddField(
            model_name='material',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='livro',
            name='genero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Genero', verbose_name='Gênero'),
            preserve_default=False,
        ),
    ]
