# Generated by Django 2.2.12 on 2021-11-26 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20211125_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='autor',
            new_name='autorL',
        ),
    ]
