# Generated by Django 2.2.12 on 2021-11-26 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_livro_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='arquivo',
            new_name='imagem',
        ),
    ]
