# Generated by Django 2.2.12 on 2021-11-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0009_auto_20211126_0507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='imagem',
            field=models.FileField(null=True, upload_to='img/'),
        ),
    ]
