# Generated by Django 2.2.12 on 2021-11-26 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0010_auto_20211126_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='imagem',
            new_name='arquivo',
        ),
    ]
