# Generated by Django 2.2.12 on 2021-11-27 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0012_auto_20211126_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='capa',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
