# Generated by Django 2.2.12 on 2021-11-27 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0013_auto_20211126_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='capa',
            new_name='arquivo',
        ),
    ]
