# Generated by Django 2.2.12 on 2021-11-27 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0016_auto_20211126_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='resumo',
            field=models.TextField(default='Resumo da Obra'),
        ),
        migrations.AlterField(
            model_name='material',
            name='livro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.Livro'),
        ),
    ]
