# Generated by Django 2.2.12 on 2021-11-27 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0017_auto_20211126_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='descricao',
            field=models.TextField(default='Resumo do Gênero', verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='edicao',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Edição'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='isbn',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='livro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Livro'),
        ),
    ]
