# Generated by Django 2.2.12 on 2021-11-27 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0018_auto_20211127_0100'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='descricao',
        ),
    ]
