# Generated by Django 2.2.12 on 2021-11-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0020_genero_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='consulta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='livro',
            name='edicao',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Edição'),
        ),
    ]
