# Generated by Django 2.2.12 on 2021-11-27 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0021_auto_20211127_0542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='curriculo_lattes',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Currículo Lattes'),
        ),
    ]
