# Generated by Django 2.2.12 on 2021-12-01 03:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cadastros', '0022_auto_20211127_0951'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acervo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtdeExemplar', models.IntegerField(default=1, verbose_name='Qtde. do Material')),
            ],
        ),
        migrations.AlterField(
            model_name='livro',
            name='consulta',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.AddField(
            model_name='acervo',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Livro'),
        ),
        migrations.AddField(
            model_name='acervo',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
