# Generated by Django 2.2.12 on 2021-12-01 03:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0023_auto_20211201_0029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livro',
            name='genero',
        ),
        migrations.AddField(
            model_name='categoria',
            name='genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Genero'),
        ),
        migrations.AddField(
            model_name='livro',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cadastros.Categoria', verbose_name='Gênero'),
        ),
        migrations.AddField(
            model_name='livro',
            name='num_page',
            field=models.IntegerField(blank=True, null=True, verbose_name='Nº Páginas'),
        ),
        migrations.AlterField(
            model_name='genero',
            name='descricao',
            field=models.CharField(max_length=20, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='edicao',
            field=models.IntegerField(default=1, verbose_name='Edição'),
        ),
    ]
