# Generated by Django 4.0.3 on 2022-11-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0028_alter_comentario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
