# Generated by Django 2.2.12 on 2021-11-28 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Biblioteca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=50, null=True)),
                ('cnpf', models.CharField(max_length=18, null=True)),
                ('telefone', models.CharField(max_length=16, null=True)),
                ('logradouro', models.CharField(max_length=60, null=True)),
                ('bairro', models.CharField(max_length=60, null=True)),
                ('cidade', models.CharField(max_length=30, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
