# Generated by Django 4.0.3 on 2022-12-05 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, null=True)),
                ('telefone', models.CharField(max_length=11, null=True)),
                ('logradouro', models.CharField(max_length=60, null=True)),
                ('bairro', models.CharField(max_length=60, null=True)),
                ('cidade', models.CharField(max_length=30, null=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Perfis',
            },
        ),
        migrations.CreateModel(
            name='Instituicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_instituicao', models.CharField(max_length=50, verbose_name='Biblioteca')),
                ('cnpj', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=11)),
                ('logradouro', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('Verificado', 'Verificado'), ('Não Verificado', 'Não Verificado')], default='Não Verificado', max_length=15)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Instituições',
            },
        ),
    ]
