# Generated by Django 2.2.12 on 2021-11-28 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20211127_2113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='cnpf',
            new_name='cnpj',
        ),
    ]
