# Generated by Django 2.2.12 on 2021-12-04 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20211127_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cnpj',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
