databases:
  - name: libraryceos
    databaseName: bdlibraryceos
    user: django

services:
  - type: web
    name: libraryceos
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn libraryceos.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: libraryceos
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4